#!/bin/sh

# --------------------------------------
# usernames

usernames="SonjaOfTheMoon EntropicPhantom Sidhe_Trickster SecundaSonja"
usernames="$usernames CmdrCordovaOfficial LieutenantCordova pwnz0rz pwnz1ing"
usernames="$usernames pwnz2much pwnz3r metampsychotic FelisKitty CGoddess"
usernames="$usernames MatttheRA ReverseTheStreams Reverse_The_Streams dukerex"
usernames="$usernames ItsDuckKingKarl bloodshoes AdmiralPancake"
usernames="$usernames Admiral_Pancake Admiral.Pancake Pancake_High_Admiral"
usernames="$usernames romanceconspirator apocalypseconspirator"
usernames="$usernames aardvarkconspirator silentconspirator Empress_Of_Silence"
usernames="$usernames banannaconspirator billygoatconspirator"
usernames="$usernames bobtheconspirator quixoticconspirator yellowconspirator"
usernames="$usernames yellowconspirator lemmingconspirator largeconspirator"
usernames="$usernames sillyconspirator lackadaisicialconspirator"
usernames="$usernames bouncyconspirator wildfireconspirator zygoteconspirator"
usernames="$usernames Pancomputer Anarchon DrHorrible venemous m1ndh1ve1"
usernames="$usernames Bulwark BULWARK GodsOfOlympus OITHEOI TA_DAIMONIA"
usernames="$usernames Theodore_Oien __RSPTN__ ThatOneVampChick MrE"
usernames="$usernames CaptainKoreaboo Unus_Relicuum Unum_Relicuum"
usernames="$usernames HadesRealmOfficial VladmirOrlovOfficial BBC_Official"
usernames="$usernames BuzzfeedOfficial algranon DOGFOODLID xX_RabbitFan_Xx"
usernames="$usernames giant_death_ferret WhoRemembers"
usernames="$usernames RED YELLOW GREEN BLUE PURPLE WHITE"
usernames="$usernames JUPITER HERA NEPTUNE MINERVA ARES APHRODITE"
usernames="$usernames TheRealHannah not_metampsychotic Do_I_know_this_guy"
usernames="$usernames EntropicKitten SonjaOfTheMeow purrz0rz meowtampsychotic"
usernames="$usernames AdogmiralPanbark Adogmiral_Panbark Dellis"
usernames="$usernames DefinitelyNotAnUmbrella Seabiscuit Arbiter"
usernames="$usernames TempShoulderAngel _TempShoulderAngel"
usernames="$usernames HotFuzzFacts HotFuzzFacts2 HotFuzzFacts3 HotFuzzFacts4"
usernames="$usernames HotFuzzFacts5 HotFuzzFacts6 HotFuzzFacts7 HotFuzzFacts8"
usernames="$usernames HotFuzzFacts9 HotFuzzFacts413 HotFuzzFacts414"
usernames="$usernames HotFuzzFacts415 HotFuzzFacts416"
usernames="$usernames KittenLicks Xenocartographer GAIA etamnanki"
usernames="$usernames SansFinalGuardian SansOfTheUnderground SansTheComic"
usernames="$usernames endsoftime DeepDark BookOfQuantumFlux reddragonfall"
usernames="$usernames Turquoise judge_of_character Wildcat Wildcat2 __Delta__"
usernames="$usernames ppDeltapp Padlock Mini_coopa2 The44th Ravencorp"
usernames="$usernames CONNECT_1200 FallenLeaves Pixelknight SteveTheMewHunter"
usernames="$usernames Stargazer TheDerangedOne russiansoldier1 russiansoldier2"
